# Generated by Django 4.2.7 on 2025-12-24 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.PositiveIntegerField(help_text='В минутах', verbose_name='Время приготовления')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='medium', max_length=10, verbose_name='Сложность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Изображение')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='Популярность')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('preferences', models.TextField(blank=True, verbose_name='Предпочтения/аллергии')),
                ('favorite_dishes', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.dish', verbose_name='Любимые блюда')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='HolidayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('number_of_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('guests', models.ManyToManyField(blank=True, to='core.guest', verbose_name='Гости')),
            ],
            options={
                'verbose_name': 'Праздничное мероприятие',
                'verbose_name_plural': 'Праздничные мероприятия',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit', models.CharField(choices=[('g', 'грамм'), ('kg', 'килограмм'), ('ml', 'миллилитр'), ('l', 'литр'), ('pcs', 'штук'), ('tbsp', 'столовая ложка'), ('tsp', 'чайная ложка')], max_length=10, verbose_name='Единица измерения')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Средняя цена')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='core.holidayevent')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.FloatField(verbose_name='Требуемое количество')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ориентировочная стоимость')),
                ('purchased', models.BooleanField(default=False, verbose_name='Куплено')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shoppinglist')),
            ],
            options={
                'verbose_name': 'Элемент списка покупок',
                'verbose_name_plural': 'Элементы списка покупок',
            },
        ),
        migrations.CreateModel(
            name='SelectedDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество порций')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.holidayevent')),
            ],
            options={
                'verbose_name': 'Выбранное блюдо',
                'verbose_name_plural': 'Выбранные блюда',
                'unique_together': {('event', 'dish')},
            },
        ),
        migrations.AddField(
            model_name='holidayevent',
            name='selected_dishes',
            field=models.ManyToManyField(through='core.SelectedDish', to='core.dish', verbose_name='Выбранные блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dishtype', verbose_name='Тип блюда'),
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Примечания')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='core.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'verbose_name': 'Ингредиент блюда',
                'verbose_name_plural': 'Ингредиенты блюд',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
    ]
